
###############################################################################
#
# Inclusive Makefile for the indigo-opennsl-driver module.
#
# Autogenerated 2016-05-04 04:23:53.711785
#
###############################################################################
indigo-opennsl-driver_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

