
###############################################################################
#
# Inclusive Makefile for the indigo_opennsl_driver module.
#
# Autogenerated 2016-05-04 04:57:32.173306
#
###############################################################################
indigo_opennsl_driver_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(indigo_opennsl_driver_BASEDIR)/module/make.mk
include $(indigo_opennsl_driver_BASEDIR)/module/auto/make.mk
include $(indigo_opennsl_driver_BASEDIR)/module/src/make.mk
include $(indigo_opennsl_driver_BASEDIR)/utest/_make.mk

